sms/feature/integration tests
Genresal/PBJ pull request #28
Opened 2023-07-28 07:59 UTC by kalachck

2023-07-31 09:10 UTC, Genresal requested changes

2023-07-31 09:10 UTC, Genresal commented on StoreManagementService/tests/PBJ.StoreManagementService.Api.IntegrationTests/ControllerTests/Abstract/BaseControllerTest.cs
>      public abstract class BaseControllerTest
Could we try to exclude all the tests folder from coverage? I mean direct inside the pipeline configuration.

2023-07-31 09:10 UTC, Genresal commented on StoreManagementService/tests/PBJ.StoreManagementService.Api.IntegrationTests/ControllerTests/Abstract/BaseControllerTest.cs
> +
I remember we discussed it, but finally there is a lot of duplicated code, could we use method (post, get, etc) as parameter and build `HttpRequestMessage` and then use `httpClient.SendAsync(request);`

2023-07-31 11:58 UTC, Genresal approved these changes

2023-08-02 07:20 UTC, Glipchik requested changes

2023-08-02 07:20 UTC, Glipchik commented on StoreManagementService/tests/PBJ.StoreManagementService.Api.IntegrationTests/ControllerTests/PostControllerTests.cs
> +        [InlineData(1)]
There is no need in using this attribute for only one data case. Either add more cases, or move this to constant in the case or outside of it

2023-08-02 07:20 UTC, Glipchik commented on .github/workflows/sonarcloud.yml
> +            **/Configuration/*, **/FixtureCustomizations/*, **/Managers/*, **/ControllerTests/**/"
Why controller tests are excluded from coverage? :)

2023-08-02 08:41 UTC, Glipchik approved these changes

2023-08-02 08:42 UTC, merged